module Yard2rbs
  class Converter
    def self.convert: (String input_path) -> String
    def initialize: (String input_path) -> void
    def convert: () -> String
    private
    def process: (Prism::Node node) -> true
    def validate: (String output) -> true
    def output: (String str) -> String
    def self?: (Prism::Node node) -> Boolean
    def parse_comments: (Prism::Node node) -> Hash
    def format_types: (Array[String] types) -> String
  end
end
